import fs from 'node:fs';
const html=fs.readFileSync(new URL('../app/index.html',import.meta.url),'utf8');
const css=fs.readFileSync(new URL('../app/css/app.css',import.meta.url),'utf8');
const init=fs.readFileSync(new URL('../app/js/init.js',import.meta.url),'utf8');
let fail=0; const check=(n,c)=>{console.log(c?'PASS':'FAIL',n);if(!c)fail++;};
const toolbar=html.indexOf('class="board-primary-toolbar"');
const week=html.indexOf('id="weekBar"');
const board=html.indexOf('class="board"',week);
const advanced=html.indexOf('id="boardAdvancedPanels"');
check('compact primary toolbar exists',toolbar>=0);
check('toolbar exposes Sort control',html.includes('id="mobileSortSel"'));
check('toolbar exposes Filters control',html.includes('id="boardFiltersBtn"'));
check('toolbar exposes More control',html.includes('id="boardMoreMenu"'));
check('week and game board now precede advanced panels',week>toolbar&&board>week&&advanced>board);
check('My Numbers is routed from More',html.includes('id="boardOpenMyNumbers"')&&init.includes('openBoardAdvanced("myNumbersPanel")'));
check('Prediction systems is routed from More',html.includes('id="boardOpenPredictionSystems"')&&init.includes('openBoardAdvanced("predPanel")'));
check('export remains available inside More',html.indexOf('id="boardExportMenu"')>html.indexOf('id="boardMoreMenu"'));
check('mobile hides advanced panels from normal flow',css.includes('.board-advanced-panels>.pred-panel{display:none;}'));
check('mobile advanced tools open as drawers',css.includes('.pred-panel.board-mobile-drawer'));
check('mobile Pick Board shell removes redundant copy',css.includes('.pickboard-shell-copy{display:none;}'));
check('filter button controls real filter panel',init.includes('filtersPanel.open=!filtersPanel.open'));
check('More supports outside-click close',init.includes('!moreMenu.contains(e.target)'));
if(fail) process.exit(1);
console.log('Pick Board mobile hierarchy regression passed.');
